sudo: false
language: c

addons:
  apt:
    packages:
    - pandoc

branches:
  only:
  - /^\d+\.\d+(\.\d+)?(-\S*)?$/


script: curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | bash -s -- -p 102603 
