sudo: false
language: c

addons:
  apt:
    packages:
    - pandoc

branches:
  only:
  - /^\d+\.\d+(\.\d+)?(-\S*)?$/

env:
  global:
  - secure: LpHyWXkrZbvOoIwSzw+Kc8c+YdI231HfOnCmql1GW4YB8gYdysPiLuTPwGg4izqdGpQosdAJAwJUBc/cEfS0/YSWJJ2NqUZqA14AzHAQ/5LGGI/3bxb++P3dYwKtp+lE86212H8prjg1ju+N8J8lNEJMM6vTxAzJ2HWFS0B5wcwiqDK+bg1O0CIETk50MHfuUb2qBVVLm/3clBWP+s1TBPt7jCtbvEXrMgS68hCFQRcqKiRAlubnBOnQFi4u7SVkOkGnk17pqcmq0/6t9fjJXEyF7sxzGlsgqYy2aXqx4/vBPm007IF34ZNxN/rUO+KpgsHVV2jqn9A+mVXCfKCvJpy6fqvpTkSN/G3lC9lUhVaXZjqXs1xjHkwR06rA468agd3afJ3Z6SnyeIG9Dg+RerEzicsjZkNHdx4YoWunnoNb9zBw26LzuZtoMCsnCBT0d1zG9WCqhpjJ5TerSs45IWlIqxqfHKrWQYOzAMY4JV3d9w6ojDQQcq0M1KQZw5l+V/j2RlAOP4CnH7uClG5BPMkiW69Ob54xqEXg/cV3qZAxwKEizoJpdJnhrNkcG8J9tu21eoWnsYurMzifpmWewdOm6lNm/20xvziJZXfO3Xx+mJF5Hjq/EcUpNr4U09D+iQG02sc85d+5CkH5wYEDbVKnkKcUSmir1AQarmsDdJo=
  - secure: QMXn3GLDaMbhAUHbQKC+JWGBpkSGGZbik4tEY+yeAZd/Jvcru4inc4OpIF9F7YYypNDqxGStQdcIxqnozSxbIXwNC1OJMOpNGBxliB6I0OFmPdx0RnOZwUKyMfMa8Iq4kbFy+nvuVwpK+o1STrwgtaWs1Z1O0lsum4F9ps0E4KaxwYUQ2hZhz6KdWO8w9vLUZelTuxTdsncN7GKAj7dnm2aRSx0q0HcTsY4wV6JJjTkC8uFYpQgUX9Sb8hc0mkY2hOI/1S+ysJ8Hmvb7g7fOvInRj7ity/BF24E3AZin6E3Hu+SauqifGH48W8/ZrSx0Yn2AtdAvug0nBNJ6B9Y7/WRUytYJmyJmF+xnmpzGX3/af8qMgff5QvsDfPEjAD/Y/EGtshPoTI6NewZfNe1qkr9gOs9gKqEJnvxEMJ2obOoZ0DpeWTWVeHudWwjWdbahmDzc8kU2Sm9NXNwZpURyRq/gPbEa8HetLzSeoDf13SL06FNAhaLUgJ9fiQ15eAitZQVA1ANAEmzUeEoy6t0i8cJAoqL/AzSYaEdli20ignuzSbfmz3ukoGbU5aTdKy32aUrrbpRUvL8FKU/B2Jl4xYkuulwDCqTFqFmUznAWOmyzyXQ9IvcUxLnQaYWfXRl9RVVVbRuiHap9XLJ6mV1VVNQx0AREaoDJmdZ8NAYgCLY=

script: curl -s https://raw.githubusercontent.com/oUF-wow/packager/master/release.sh | bash

notifications:
  email:
    on_success: always
    on_failure: always
    recipients:
    - secure: dJxvLi337rZrem9YDyhOIFg4cb/+GJLqBwZ7H/ovbalP9Sw63tCpTIwq5HZ3/iDVrLH5DyOv//SHOqikBO/ZbCwG/uAr3rMsAlbibAS9yukg+mpzbP7J7DscQkJnjXmg+JEPzUu+pXoR+2eXpdPRJ9pJoQJ4hSyLmZaGkmps3aRR1o1VcSYqZZSsR1wnNIbWlI0xsHV++Eb045tDWurhLrVcMJsKZx69DjwzIKaHjyULXLs8PgMVOm76LUa8MWSxbx4Cw2vRAxJro79NM79CqEigGzyHAHQEQ+nobxCqRaf7SjQikCDK785PZF2sk796+3zfyYH8O24YxFzMrKdtfaVeTi4enkqqXPc6p8JV1Yku/OGNOVe6kRm66Y/WjDn/S/wlxfPXhLSeya8PuX8aaU4Wv5eWiYtRIl3ddTyYbE3nFkpqiotzPRA/gJqx2j+n7XZ2sLxVaUH8wqULkFA/1vnOt/KFFzeiGuTIU/d8mDS7TclNFi+fLE74BqWzQ4sPt4+uNrhxG8N8CU4W0SCPuX1s8O5jtDv8pocMYBJhdG3WsQPLv4RF/SpSOqc/+eM9ag/OPUhjkIvO6tNJqF4uFmxXoOiEmlD66svuxGwdBr1xXMrHcnQwr0NzlZcWZBeacznlyZM2OtMAJTaHNujnKGwCnWHVNW6BD5/PlInDvQA=
